# Generated by Django 5.0.1 on 2024-01-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petid', models.IntegerField(primary_key=True, serialize=False)),
                ('petname', models.CharField(max_length=50)),
                ('petgender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=20)),
                ('petage', models.IntegerField()),
                ('petdescription', models.TextField(max_length=200)),
                ('petphoto', models.ImageField(upload_to='images')),
            ],
        ),
    ]
